name: Build Resourcepack

on:
  push:
    branches:
      - master   # oder master, je nach Branch
    tags:
      - 'v*'   # erstellt ein Release bei Tags wie v1.0, v1.1 etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pack resourcepack into zip
        run: |
          zip -r PluginResourcePack.zip assets pack.mcmeta

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: PluginResourcePack.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
